name: gha-check-release-exists
author: Alex Vincent
description: Checks if a github release exists.

inputs:
  GITHUB_TOKEN:
    description: i.e. secrets.GITHUB_TOKEN
    required: true
  ReleaseName:
    description: i.e. '1.2.2' or '1.2.2-2022-04-ci-updates.13'
    required: true

outputs:
  ReleaseExists:
    description: i.e. True or False
    value: ${{ steps.check-release.outputs.ReleaseExists }}

runs:
  using: composite
  steps:
    - id: check-release
      name: github-check-release
      #TODO: rewrite Invoke-CheckReleaseExists.ps1 to be a shell script
      shell: pwsh
      run: |
        $ReleaseExists = &"${{ github.action_path }}/.scripts/Invoke-CheckReleaseExists.ps1" `
          -ReleaseName ${{ inputs.ReleaseName }}
        echo "ReleaseExists=$ReleaseExists" >> $env:GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
